### ISSUE TITLE
Add more airport

### ISSUE THREAD

**Issue by ghost** [crzran/VATPRC-VFPC#1]
Way not add more airport? I think that is a very good plugin for the DEL ATC!

**Comment by crzran** [comment]
Thank you for your suggestion. A new version is already completed, which includes amendment to ZSPD SOP and flight plan checking for ZBAA according to the latest SOP. As I have been extremely occupied irl recently, I did not upload it onto Github. I will be uploading the new version in an hour. Thank you for your support for the VFPC plugin.

Warm Regards,
Ran Chen
